version: '3.0'

# Ignore this`expectation` block. It is required but not used, and will be removed in future versions.
expectations:
  population_size: 1000

actions:
  generate_dataset_codes:
    run: >
      ehrql:v1
        generate-dataset analysis/dataset_definition_clinical_codes.py
        --test-data-file analysis/test_dataset_definition_clinical_codes.py
        --dummy-tables dummy_tables
        --output output/data_curation/data_curation.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/data_curation/data_curation.csv.gz
  
  generate_measures_codes:
    run: > 
      ehrql:v1 generate-measures analysis/measures_definition_clinical_codes.py
      --dummy-tables dummy_tables
      --output output/clinical_codes/code_counts_measures.csv
    outputs:
      moderately_sensitive:
        measure: output/clinical_codes/code_counts_measures.csv

  generate_dataset_curation:
    run: >
      ehrql:v1 generate-dataset analysis/dataset_definition_curation.py
        --test-data-file analysis/test_dataset_definition_curation.py
        --dummy-tables dummy_tables
        --output output/data_curation/medications_data_curation.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/data_curation/medications_data_curation.csv.gz

  data_curation_medications:
    run: r:latest analysis/data_curation_medications_table.R
    needs: [generate_dataset_curation]
    outputs:
      moderately_sensitive:
        dataset: output/data_curation/medication_status_counts.csv
