version: '5.0'

actions:

  generate_med_status_data_development:
    run: >
      ehrql:v1 generate-dataset analysis/dataset_definition_med_status_data_development.py
        --output output/data_development/med_status_data_development.arrow
    outputs:
      highly_sensitive:
        dataset: output/data_development/med_status_data_development.arrow

  generate_med_status_data_development_fixed:
    run: >
      ehrql:v1 generate-dataset analysis/dataset_definition_med_status_data_development_fixed.py
        --output output/data_development/med_status_data_development_fixed.arrow
    outputs:
      highly_sensitive:
        dataset: output/data_development/med_status_data_development_fixed.arrow

  generate_measures_pf_codes:
    run: > 
      ehrql:v1 generate-measures analysis/measures_definition_clinical_codes.py
      --output output/clinical_codes/code_counts_measures.csv
    outputs:
      moderately_sensitive:
        measure: output/clinical_codes/code_counts_measures.csv

  data_development_med_status_pre:
     run: r:v2 analysis/data_development_med_status_pre_counts.R
     needs: [generate_med_status_data_development]
     outputs:
       moderately_sensitive:
         dataset: output/data_development/med_status_pre_counts.csv
  
  data_development_med_status_post:
     run: r:v2 analysis/data_development_med_status_post_counts.R
     needs: [generate_med_status_data_development]
     outputs:
       moderately_sensitive:
         dataset: output/data_development/med_status_post_counts.csv
    
  data_development_med_status_post_fixed:
      run: r:v2 analysis/data_development_med_status_post_counts_fixed.R
      needs: [generate_med_status_data_development_fixed]
      outputs:
        moderately_sensitive:
          dataset: output/data_development/med_status_post_counts_fixed.csv

  data_development_med_status_combine:
     run: r:v2 analysis/data_development_med_status_combine.R
     needs: [data_development_med_status_pre, data_development_med_status_post]
     outputs:
       moderately_sensitive:
         dataset: output/data_development/med_status_counts.csv

  generate_pf_med_counts_measures:
    run: >
      ehrql:v1 generate-measures analysis/measures_definition_pf_consultation_med_counts.py
      --dummy-tables dummy_tables
      --output output/measures/consultation_med_counts_measures.csv
    outputs:
      moderately_sensitive:
        measure: output/measures/consultation_med_counts_measures.csv

  generate_med_status_counts_measures:
    run: >
      ehrql:v1 generate-measures analysis/measures_med_status_counts.py
      --output output/measures/measures_med_status_counts.csv
    outputs:
      moderately_sensitive:
        measure: output/measures/measures_med_status_counts.csv
