version: '3.0'

# Ignore this`expectation` block. It is required but not used, and will be removed in future versions.
expectations:
  population_size: 1000

actions:

  generate_measures_codes:
    run: > 
      ehrql:v1 generate-measures analysis/measures_definition_clinical_codes.py
      --dummy-tables dummy_tables
      --output output/clinical_codes/code_counts_measures.csv
    outputs:
      moderately_sensitive:
        measure: output/clinical_codes/code_counts_measures.csv
