version: '3.0'

# Ignore this`expectation` block. It is required but not used, and will be removed in future versions.
expectations:
  population_size: 1000

actions:
  generate_pf_data_development:
    run: >
      ehrql:v1 generate-dataset analysis/dataset_definition_pf_data_development.py
        --test-data-file analysis/test_dataset_definition_pf_data_development.py
        --dummy-tables dummy_tables
        --output output/data_development/pharmacy_first_data_development.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/data_development/pharmacy_first_data_development.csv.gz

  generate_med_status_data_development:
    run: >
      ehrql:v1 generate-dataset analysis/dataset_definition_med_status_data_development.py
        --dummy-tables dummy_tables
        --output output/data_development/med_status_data_development.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/data_development/med_status_data_development.csv.gz

  generate_measures_codes:
    run: > 
      ehrql:v1 generate-measures analysis/measures_definition_clinical_codes.py
      --dummy-tables dummy_tables
      --output output/clinical_codes/code_counts_measures.csv
    outputs:
      moderately_sensitive:
        measure: output/clinical_codes/code_counts_measures.csv

  data_curation_medications:
    run: r:latest analysis/data_curation_medications_table.R
    needs: [generate_pf_data_development]
    outputs:
      moderately_sensitive:
        dataset: output/data_curation/medication_status_counts.csv

  data_curation_consultations:
    run: r:latest analysis/data_curation_pharmacy_first_consultations.R
    needs: [generate_pf_data_development]
    outputs:
      moderately_sensitive:
        dataset: output/data_curation/consultations_counts.csv