version: '3.0'

# Ignore this`expectation` block. It is required but not used, and will be removed in future versions.
expectations:
  population_size: 1000

actions:
  generate_pf_codes_data_development:
    run: >
      ehrql:v1 generate-dataset analysis/dataset_definition_pf_data_development.py
        --test-data-file analysis/test_dataset_definition_pf_data_development.py
        --dummy-tables dummy_tables
        --output output/data_development/pf_codes_data_development.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/data_development/pf_codes_data_development.csv.gz

  generate_med_status_data_development:
    run: >
      ehrql:v1 generate-dataset analysis/dataset_definition_med_status_data_development.py
        --dummy-tables dummy_tables
        --output output/data_development/med_status_data_development.arrow
    outputs:
      highly_sensitive:
        dataset: output/data_development/med_status_data_development.arrow

  generate_measures_pf_codes:
    run: > 
      ehrql:v1 generate-measures analysis/measures_definition_clinical_codes.py
      --dummy-tables dummy_tables
      --output output/clinical_codes/code_counts_measures.csv
    outputs:
      moderately_sensitive:
        measure: output/clinical_codes/code_counts_measures.csv

  data_development_med_status:
     run: r:latest analysis/data_development_med_status_counts.R
     needs: [generate_med_status_data_development]
     outputs:
       moderately_sensitive:
         dataset: output/data_development/med_status_counts.csv

  data_development_pf_codes:
    run: r:latest analysis/data_development_pf_code_counts.R
    needs: [generate_pf_codes_data_development]
    outputs:
      moderately_sensitive:
        dataset: output/data_development/pf_codes_counts.csv