---
title: "Pharmacy First Data Development Report"
output: html_document
---

This markdown report creates the tables and figures for the **Pharmacy First Data Development** project. 

```{r setup, include=FALSE}
library(tidyverse)
library(here)
library(gt)
```

```{r load-data, include=FALSE}
output_dir <- "released_output"
df_med_status_counts <- read_csv(
  here(output_dir, "data_development", "med_status_counts.csv")
)
df_pf_codes_counts <- read_csv(
  here(output_dir, "data_development", "pf_codes_counts.csv")
)
df_codes_counts <- read_csv(
  here(output_dir, "clinical_codes", "code_counts_measures.csv")
)
```

```{r tidy-data, include=FALSE}
# Medication status labels and descriptions
med_status_label <- paste0("status", 0:28)

med_status_label_desc <- c(
  "0 - Normal",
  NA_character_, NA_character_, NA_character_,
  "4 - Historical",
  "5 - Blue script",
  "6 - Private",
  "7 - Not in possession",
  "8 - Repeat dispensed",
  "9 - In possession",
  "10 - Dental",
  "11 - Hospital",
  "12 - Problem substance",
  "13 - From patient group direction",
  "14 - To take out",
  "15 - On admission",
  "16 - Regular medication",
  "17 - As required medication",
  "18 - Variable dose medication",
  "19 - Rate-controlled single regular",
  "20 - Only once",
  "21 - Outpatient",
  "22 - Rate-controlled multiple regular",
  "23 - Rate-controlled multiple only once",
  "24 - Rate-controlled single only once",
  "25 - Placeholder",
  "26 - Unconfirmed",
  "27 - Infusion",
  "28 - Reducing dose blue script"
)
unique(df_codes_counts$measure)
# Pharmacy first codes
pf_consultation_label <- c(
  "count_blood_pressure_service",
  "count_contraception_service",
  "count_consultation_service",
  "count_pharmacy_first_service"
)

pf_consultation_label_desc <- c(
  "Blood Pressure Check Service (1659111000000107)",
  "Contraception Service (1659121000000101)",
  "Consultation Service for minor illness (1577041000000109)",
  "Pharmacy First service (983341000000102)"
)
```

## Pharmacy First medication status

```{r, message=FALSE, warning=FALSE, echo = FALSE}
# Process data frame
df_tab_med_status_counts <- df_med_status_counts %>%
  replace_na(list(n = 0)) %>%
  pivot_wider(names_from = c(time, selected_codes), values_from = n) %>%
  mutate(
    pre_pfmedid = NA,
    med_status = factor(
      med_status,
      levels = med_status_label,
      labels = med_status_label_desc
    )
  ) %>%
  relocate(
    med_status,
    pre_any, pre_pfmed, pre_pfmedid,
    post_any, post_pfmed, post_pfmedid
  )

# Display data frame as table
tab_med_status_counts <- df_tab_med_status_counts %>%
  gt() %>%
  sub_missing(
    columns = everything(),
    rows = everything(),
    missing_text = "---"
  ) %>%
  fmt_number(
    columns = c(
      pre_any,
      pre_pfmed,
      pre_pfmedid,
      post_any,
      post_pfmed,
      post_pfmedid
    ),
    decimals = 0
  ) %>%
  tab_spanner(
    label = "6 months pre PF launch",
    columns = starts_with("pre_")
  ) %>%
  tab_spanner(
    label = "6 months post PF launch",
    columns = starts_with("post_")
  ) %>%
  cols_label(
    med_status = "Medication status",
    pre_any = "Any",
    pre_pfmed = "PF Med",
    pre_pfmedid = "PF Med & Consult",
    post_any = "Any",
    post_pfmed = "PF Med",
    post_pfmedid = "PF Med & Consult"
  ) %>%
  cols_align(
    align = "left",
    columns = med_status
  ) %>%
  tab_footnote(
    footnote = "Any medication.",
    locations = cells_column_labels(columns = c(pre_any, post_any))
  ) %>%
  tab_footnote(
    footnote = "Pharmacy First medications.",
    locations = cells_column_labels(columns = c(pre_pfmed, post_pfmed))
  ) %>%
  tab_footnote(
    footnote = "Pharmacy First medications and Pharmacy First consultation.",
    locations = cells_column_labels(columns = c(pre_pfmedid, post_pfmedid))
  ) %>%
  tab_header(
    title = md("**Count of medication status before and after the Pharmacy First launch date (31 Jan 2024)**"),
  )

gtsave(
  tab_med_status_counts,
  here("reports", "resources", "tab_med_status_counts.png"),
)

tab_med_status_counts
```

## Pharmacy First consultation codes

```{r, fig.height=5, fig.width=8, echo = FALSE, warning=FALSE}
# Read the CSV file

plot_code_counts <- df_codes_counts %>%
  group_by(measure, interval_end) %>%
  mutate(
    numerator_total = sum(numerator, na.rm = TRUE),
    denominator_total = sum(denominator, na.rm = TRUE),
    measure = factor(measure, levels = pf_consultation_label, labels = pf_consultation_label_desc),
  ) %>%
  select(measure, interval_end, numerator_total, denominator_total) %>%
  distinct() %>%
  ggplot(aes(
    x = interval_end,
    y = numerator_total,
    colour = measure,
    shape = measure,
  )) +
  geom_point(size = 2) +
  geom_line(alpha = .3) +
  labs(
    title = NULL,
    x = NULL,
    y = "Total count",
    colour = NULL,
    shape = NULL
  ) +
  scale_y_continuous(
    labels = scales::label_number(),
  ) +
  theme(legend.position = "bottom") +
  guides(
    colour = guide_legend(ncol = 2),
    shape = guide_legend(ncol = 2)
  ) +
  scale_x_date(
    date_breaks = "1 month",
    labels = scales::label_date_short()
  ) +
  geom_vline(
    xintercept = lubridate::as_date(c(
      "2024-01-31"
    )),
    linetype = "dotted",
    colour = "orange",
    size = .7
  ) +
  scale_colour_viridis_d(end = .75)

ggsave(
  here("reports", "resources", "plot_code_counts.png"),
  plot_code_counts,
  height = 5,
  width = 8
)

plot_code_counts
```

```{r, fig.height=12, fig.width=8, echo = FALSE, warning=FALSE}
# Read the CSV file

# Process data frame
plot_code_counts_region <- df_codes_counts %>%
  replace_na(list(practice_region = "(Missing)")) %>%
  mutate(
    measure = factor(measure, levels = pf_consultation_label, labels = pf_consultation_label_desc),
    practice_region = fct_relevel(practice_region, "(Missing)", after = Inf)
  ) %>%
  ggplot(aes(
    x = interval_end,
    y = ratio,
    colour = practice_region,
  )) +
  geom_point() +
  geom_line(alpha = .3) +
  labs(
    title = NULL,
    x = NULL,
    y = "Ratio of counts",
    colour = NULL
  ) +
  scale_y_continuous(
    labels = scales::label_percent(),
  ) +
  facet_wrap(~measure,
    scales = "free_y",
    ncol = 1
  ) +
  scale_colour_brewer(palette = "Set1", na.value = "#000000") +
  theme(legend.position = "bottom") +
  scale_x_date(
    date_breaks = "1 month",
      labels = scales::label_date_short()
    ) +
    geom_vline(
      xintercept = lubridate::as_date(c(
        "2024-01-31"
      )),
      linetype = "dotted",
      colour = "orange",
      size = .7
    )

ggsave(
  here("reports", "resources", "plot_code_counts_region.png"),
  plot_code_counts_region,
  height = 12,
  width = 8
)

plot_code_counts_region
```
